kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: pega-ext-secrets-cred
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    {{- range $key, $val := .Values.global.env.externalsecret }}
    - key: $val
      name: $key
    {{- end }}